In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('./nouns.csv', sep='\t', header=None)

# ['deutsch', 'english', 'aussprache', 'genus', 'plural', 'biespeal', 'deutsch_audio', 'plural_audio', 'full_noun']

df

             0                  1   2    3   4   5   6   7   8
0      Bereich               area NaN  der NaN NaN NaN NaN NaN
1      Gitarre             guitar NaN  die NaN NaN NaN NaN NaN
2       Tennis             tennis NaN  das NaN NaN NaN NaN NaN
3   Volleyball         volleyball NaN  der NaN NaN NaN NaN NaN
4     Programm            program NaN  das NaN NaN NaN NaN NaN
..         ...                ...  ..  ...  ..  ..  ..  ..  ..
94      Risiko       hazard; risk NaN  das NaN NaN NaN NaN NaN
95   Beziehung       relationship NaN  die NaN NaN NaN NaN NaN
96        Kauf           purchase NaN  der NaN NaN NaN NaN NaN
97        Spaß                fun NaN  der NaN NaN NaN NaN NaN
98      Unsinn  nonsense; rubbish NaN  der NaN NaN NaN NaN NaN

[99 rows x 9 columns]

In [56]:
def merg_func(row):
    genus=row[3]
    deutch=row[0]
    return f"{genus} {deutch}" if genus else deutch

df[8] = df[[0,3]].fillna('').apply(merg_func, axis='columns')

In [57]:
df

             0                  1   2    3   4   5   6   7               8
0      Bereich               area NaN  der NaN NaN NaN NaN     der Bereich
1      Gitarre             guitar NaN  die NaN NaN NaN NaN     die Gitarre
2       Tennis             tennis NaN  das NaN NaN NaN NaN      das Tennis
3   Volleyball         volleyball NaN  der NaN NaN NaN NaN  der Volleyball
4     Programm            program NaN  das NaN NaN NaN NaN    das Programm
..         ...                ...  ..  ...  ..  ..  ..  ..             ...
94      Risiko       hazard; risk NaN  das NaN NaN NaN NaN      das Risiko
95   Beziehung       relationship NaN  die NaN NaN NaN NaN   die Beziehung
96        Kauf           purchase NaN  der NaN NaN NaN NaN        der Kauf
97        Spaß                fun NaN  der NaN NaN NaN NaN        der Spaß
98      Unsinn  nonsense; rubbish NaN  der NaN NaN NaN NaN      der Unsinn

[99 rows x 9 columns]

In [61]:
df.to_csv('nouns_output.csv', index=None, header=None)